### ISSUE TITLE
Python script

### ISSUE THREAD

**Issue by pwang16** [ParkinsonLab/2017-Microbiome-Workshop#1]
Dear Mobolaji Adeolu,

Thank you very much for sharing the Metatranscriptomics pipeline in the github "2017-Microbiome-Workshop". I am a newcomer for the study of microbial metatranscriptomics. Your pipeline helps me understand the data analysis of Metatranscriptomics a lot.

I have a couple of questions: (1)could you please share the  1_BLAT_Filter.py online? (2) I am getting stuck at the "step 4. remove host reads". I got error information:Unable to read from file (mouse1_mouse_bwa.fastq). I think "samtools fastq -n -f 4 -0 mouse1_mouse_bwa.fastq mouse1_mouse_bwa.bam" did not generate it correctly, right?

Best regards,

Peng Wang

**Comment by billyc59** [comment]
Hi Peng,
The files you're looking for are all inside the precomputed_files.tar.gz
