### ISSUE TITLE
TypeError: unhashable type: 'SeqRecord'

### ISSUE THREAD

**Issue by pwang16** [ParkinsonLab/2017-Microbiome-Workshop#2]
Hi Billy Taj,

Thanks a lot for your reply.
I have a problem after I run the command in the  Step 5–Remove abundant rRNA sequences: 
./2_Infernal_Filter.py mouse1_mouse_blat.fastq mouse1_rRNA.infernalout mouse1_unique_mRNA.fastq mouse1_unique_rRNA.fastq

After I return and run it, It shows:

Traceback (most recent call last):
  File "./2_Infernal_Filter.py", line 33, in <module>
    mRNA_seqs.add(sequence)
TypeError: unhashable type: 'SeqRecord'

What can i do next?
Best regards,
Peng

**Comment by billyc59** [comment]
which step is this?

**Comment by pwang16** [comment]
Step 5–Remove abundant rRNA sequences.

I am sure I have installed the BioPython.

**Comment by billyc59** [comment]
I just reran the tutorial from step 1 through to 5.  I see no errors.  can you comfirm that every other step happened without incident?

**Comment by pwang16** [comment]
Okay. Thanks very much for your time and reply. I can do it and to see if other steps have incident or not.

Best regards,
Peng

**Comment by billyc59** [comment]
closed due to bad placement of issue.

**Comment by billyc59** [comment]
sorry, didn't realize you left a question:
This tutorial was meant as a standalone workshop demo.  It's only guaranteed to work with the pre-computed files we supplied.  As you can tell, there's many variations that are possible, so we can't really guarantee that this particular workshop is flexible enough for your specific needs, without your personal intervention.  

That being said, we're aware of the situation, and we're working on something to address this.
