### ISSUE TITLE
0 genes were mapped with Diamond---step 10

### ISSUE THREAD

**Issue by pwang16** [ParkinsonLab/2017-Microbiome-Workshop#3]
Hi Billy Taj,

I stoped at the Step10 when I use "./8_Gene_EC_Map.py". It shows the error information:
"0 genes were mapped with Diamond to 0 unique enzyme functions."

Does swiss_map.tsv belonging to the old version cause the 0 genes mapped? Because I downloaded the new swiss_db database.

Thanks,
Peng

**Comment by billyc59** [comment]
yes.  it was built for a specific version of DIAMOND.  you'll want to use v0.826
